version: 2
updates:
  - package-ecosystem: "npm"
    schedule:
      interval: "daily"
    groups:
      angular-packages:
        patterns:
          - "@angular/*"
          - "@taiga-ui/*"
          - "zone.js"
          - "rxjs"
