version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      angular-packages:
        patterns:
          - "@angular/*"
          - "zone.js"
          - "rxjs"
      dev-dependencies:
        patterns:
          - "@angular-eslint/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "prettier"
          - "typescript"
          - "karma*"
          - "jasmine*"
